package goguessocuntry

// Code generated from official ISO country lists and countryguess regex mappings.
// DO NOT EDIT MANUALLY.

var goguesscountries = []Country{
    {Name: "Andorra", FormalName: "Principality of Andorra", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "AD", ISO3: "AND", Continent: "Europe", RegionUN: "Europe", Subregion: "Southern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "United Arab Emirates", FormalName: "United Arab Emirates", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "AE", ISO3: "ARE", Continent: "Asia", RegionUN: "Asia", Subregion: "Western Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Afghanistan", FormalName: "Islamic Republic of Afghanistan", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "AF", ISO3: "AFG", Continent: "Asia", RegionUN: "Asia", Subregion: "Southern Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Antigua and Barbuda", FormalName: "Antigua and Barbuda", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "AG", ISO3: "ATG", Continent: "North America", RegionUN: "America", Subregion: "Caribbean", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Anguilla", FormalName: "Anguilla", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "AI", ISO3: "AIA", Continent: "North America", RegionUN: "America", Subregion: "Caribbean", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Albania", FormalName: "Republic of Albania", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "AL", ISO3: "ALB", Continent: "Europe", RegionUN: "Europe", Subregion: "Southern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Armenia", FormalName: "Republic of Armenia", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "AM", ISO3: "ARM", Continent: "Asia", RegionUN: "Asia", Subregion: "Western Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Angola", FormalName: "Republic of Angola", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "AO", ISO3: "AGO", Continent: "Africa", RegionUN: "Africa", Subregion: "Middle Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Antarctica", FormalName: "Antarctica", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "AQ", ISO3: "ATA", Continent: "Antarctica", RegionUN: "Antarctica", Subregion: "Antarctica", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Argentina", FormalName: "Argentine Republic", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "AR", ISO3: "ARG", Continent: "South America", RegionUN: "America", Subregion: "South America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "American Samoa", FormalName: "American Samoa", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "AS", ISO3: "ASM", Continent: "Oceania", RegionUN: "Oceania", Subregion: "Polynesia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Austria", FormalName: "Republic of Austria", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "AT", ISO3: "AUT", Continent: "Europe", RegionUN: "Europe", Subregion: "Western Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Australia", FormalName: "Australia", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "AU", ISO3: "AUS", Continent: "Oceania", RegionUN: "Oceania", Subregion: "Australia and New Zealand", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Aruba", FormalName: "Aruba", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "AW", ISO3: "ABW", Continent: "North America", RegionUN: "America", Subregion: "Caribbean", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Åland Islands", FormalName: "Åland Islands", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "AX", ISO3: "ALA", Continent: "Europe", RegionUN: "Europe", Subregion: "Northern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Azerbaijan", FormalName: "Republic of Azerbaijan", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "AZ", ISO3: "AZE", Continent: "Asia", RegionUN: "Asia", Subregion: "Western Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Bosnia and Herzegovina", FormalName: "Republic of Bosnia and Herzegovina", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "BA", ISO3: "BIH", Continent: "Europe", RegionUN: "Europe", Subregion: "Southern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Barbados", FormalName: "Barbados", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "BB", ISO3: "BRB", Continent: "North America", RegionUN: "America", Subregion: "Caribbean", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Bangladesh", FormalName: "People's Republic of Bangladesh", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "BD", ISO3: "BGD", Continent: "Asia", RegionUN: "Asia", Subregion: "Southern Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Belgium", FormalName: "Kingdom of Belgium", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "BE", ISO3: "BEL", Continent: "Europe", RegionUN: "Europe", Subregion: "Western Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Burkina Faso", FormalName: "Burkina Faso", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "BF", ISO3: "BFA", Continent: "Africa", RegionUN: "Africa", Subregion: "Western Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Bulgaria", FormalName: "Republic of Bulgaria", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "BG", ISO3: "BGR", Continent: "Europe", RegionUN: "Europe", Subregion: "Eastern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Bahrain", FormalName: "Kingdom of Bahrain", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "BH", ISO3: "BHR", Continent: "Asia", RegionUN: "Asia", Subregion: "Western Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Burundi", FormalName: "Republic of Burundi", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "BI", ISO3: "BDI", Continent: "Africa", RegionUN: "Africa", Subregion: "Eastern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Benin", FormalName: "Republic of Benin", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "BJ", ISO3: "BEN", Continent: "Africa", RegionUN: "Africa", Subregion: "Western Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Saint Barthélemy", FormalName: "Saint Barthélemy", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "BL", ISO3: "BLM", Continent: "North America", RegionUN: "America", Subregion: "Caribbean", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Bermuda", FormalName: "Bermuda", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "BM", ISO3: "BMU", Continent: "North America", RegionUN: "America", Subregion: "Northern America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Brunei Darussalam", FormalName: "Brunei Darussalam", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "BN", ISO3: "BRN", Continent: "Asia", RegionUN: "Asia", Subregion: "South-eastern Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Bolivia, Plurinational State of", FormalName: "Plurinational State of Bolivia", Abbrev: "Bolivia", NameAlt: "", Population: 0, GDP: 0, ISO2: "BO", ISO3: "BOL", Continent: "South America", RegionUN: "America", Subregion: "South America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Bonaire, Sint Eustatius and Saba", FormalName: "Bonaire, Sint Eustatius and Saba", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "BQ", ISO3: "BES", Continent: "North America", RegionUN: "America", Subregion: "Caribbean", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Brazil", FormalName: "Federative Republic of Brazil", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "BR", ISO3: "BRA", Continent: "South America", RegionUN: "America", Subregion: "South America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Bahamas", FormalName: "Commonwealth of the Bahamas", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "BS", ISO3: "BHS", Continent: "North America", RegionUN: "America", Subregion: "Caribbean", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Bhutan", FormalName: "Kingdom of Bhutan", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "BT", ISO3: "BTN", Continent: "Asia", RegionUN: "Asia", Subregion: "Southern Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Bouvet Island", FormalName: "Bouvet Island", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "BV", ISO3: "BVT", Continent: "Antarctica", RegionUN: "Antarctica", Subregion: "South America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Botswana", FormalName: "Republic of Botswana", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "BW", ISO3: "BWA", Continent: "Africa", RegionUN: "Africa", Subregion: "Southern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Belarus", FormalName: "Republic of Belarus", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "BY", ISO3: "BLR", Continent: "Europe", RegionUN: "Europe", Subregion: "Eastern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Belize", FormalName: "Belize", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "BZ", ISO3: "BLZ", Continent: "North America", RegionUN: "America", Subregion: "Central America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Canada", FormalName: "Canada", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "CA", ISO3: "CAN", Continent: "North America", RegionUN: "America", Subregion: "Northern America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Cocos (Keeling) Islands", FormalName: "Cocos (Keeling) Islands", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "CC", ISO3: "CCK", Continent: "Asia", RegionUN: "Asia", Subregion: "Australia and New Zealand", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Congo, The Democratic Republic of the", FormalName: "Congo, The Democratic Republic of the", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "CD", ISO3: "COD", Continent: "Africa", RegionUN: "Africa", Subregion: "Middle Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Central African Republic", FormalName: "Central African Republic", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "CF", ISO3: "CAF", Continent: "Africa", RegionUN: "Africa", Subregion: "Middle Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Congo", FormalName: "Republic of the Congo", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "CG", ISO3: "COG", Continent: "Africa", RegionUN: "Africa", Subregion: "Middle Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Switzerland", FormalName: "Swiss Confederation", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "CH", ISO3: "CHE", Continent: "Europe", RegionUN: "Europe", Subregion: "Western Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Côte d'Ivoire", FormalName: "Republic of Côte d'Ivoire", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "CI", ISO3: "CIV", Continent: "Africa", RegionUN: "Africa", Subregion: "Western Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Cook Islands", FormalName: "Cook Islands", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "CK", ISO3: "COK", Continent: "Oceania", RegionUN: "Oceania", Subregion: "Polynesia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Chile", FormalName: "Republic of Chile", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "CL", ISO3: "CHL", Continent: "South America", RegionUN: "America", Subregion: "South America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Cameroon", FormalName: "Republic of Cameroon", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "CM", ISO3: "CMR", Continent: "Africa", RegionUN: "Africa", Subregion: "Middle Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "China", FormalName: "People's Republic of China", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "CN", ISO3: "CHN", Continent: "Asia", RegionUN: "Asia", Subregion: "Eastern Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Colombia", FormalName: "Republic of Colombia", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "CO", ISO3: "COL", Continent: "South America", RegionUN: "America", Subregion: "South America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Costa Rica", FormalName: "Republic of Costa Rica", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "CR", ISO3: "CRI", Continent: "North America", RegionUN: "America", Subregion: "Central America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Cuba", FormalName: "Republic of Cuba", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "CU", ISO3: "CUB", Continent: "North America", RegionUN: "America", Subregion: "Caribbean", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Cabo Verde", FormalName: "Republic of Cabo Verde", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "CV", ISO3: "CPV", Continent: "Africa", RegionUN: "Africa", Subregion: "Western Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Curaçao", FormalName: "Curaçao", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "CW", ISO3: "CUW", Continent: "North America", RegionUN: "America", Subregion: "Caribbean", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Christmas Island", FormalName: "Christmas Island", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "CX", ISO3: "CXR", Continent: "Asia", RegionUN: "Asia", Subregion: "Australia and New Zealand", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Cyprus", FormalName: "Republic of Cyprus", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "CY", ISO3: "CYP", Continent: "Europe", RegionUN: "Asia", Subregion: "Western Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Czechia", FormalName: "Czech Republic", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "CZ", ISO3: "CZE", Continent: "Europe", RegionUN: "Europe", Subregion: "Eastern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Germany", FormalName: "Federal Republic of Germany", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "DE", ISO3: "DEU", Continent: "Europe", RegionUN: "Europe", Subregion: "Western Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Djibouti", FormalName: "Republic of Djibouti", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "DJ", ISO3: "DJI", Continent: "Africa", RegionUN: "Africa", Subregion: "Eastern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Denmark", FormalName: "Kingdom of Denmark", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "DK", ISO3: "DNK", Continent: "Europe", RegionUN: "Europe", Subregion: "Northern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Dominica", FormalName: "Commonwealth of Dominica", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "DM", ISO3: "DMA", Continent: "North America", RegionUN: "America", Subregion: "Caribbean", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Dominican Republic", FormalName: "Dominican Republic", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "DO", ISO3: "DOM", Continent: "North America", RegionUN: "America", Subregion: "Caribbean", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Algeria", FormalName: "People's Democratic Republic of Algeria", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "DZ", ISO3: "DZA", Continent: "Africa", RegionUN: "Africa", Subregion: "Northern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Ecuador", FormalName: "Republic of Ecuador", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "EC", ISO3: "ECU", Continent: "South America", RegionUN: "America", Subregion: "South America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Estonia", FormalName: "Republic of Estonia", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "EE", ISO3: "EST", Continent: "Europe", RegionUN: "Europe", Subregion: "Northern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Egypt", FormalName: "Arab Republic of Egypt", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "EG", ISO3: "EGY", Continent: "Africa", RegionUN: "Africa", Subregion: "Northern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Western Sahara", FormalName: "Western Sahara", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "EH", ISO3: "ESH", Continent: "Africa", RegionUN: "Africa", Subregion: "Northern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Eritrea", FormalName: "the State of Eritrea", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "ER", ISO3: "ERI", Continent: "Africa", RegionUN: "Africa", Subregion: "Eastern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Spain", FormalName: "Kingdom of Spain", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "ES", ISO3: "ESP", Continent: "Europe", RegionUN: "Europe", Subregion: "Southern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Ethiopia", FormalName: "Federal Democratic Republic of Ethiopia", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "ET", ISO3: "ETH", Continent: "Africa", RegionUN: "Africa", Subregion: "Eastern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Finland", FormalName: "Republic of Finland", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "FI", ISO3: "FIN", Continent: "Europe", RegionUN: "Europe", Subregion: "Northern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Fiji", FormalName: "Republic of Fiji", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "FJ", ISO3: "FJI", Continent: "Oceania", RegionUN: "Oceania", Subregion: "Melanesia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Falkland Islands (Malvinas)", FormalName: "Falkland Islands (Malvinas)", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "FK", ISO3: "FLK", Continent: "South America", RegionUN: "America", Subregion: "South America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Micronesia, Federated States of", FormalName: "Federated States of Micronesia", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "FM", ISO3: "FSM", Continent: "Oceania", RegionUN: "Oceania", Subregion: "Micronesia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Faroe Islands", FormalName: "Faroe Islands", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "FO", ISO3: "FRO", Continent: "Europe", RegionUN: "Europe", Subregion: "Northern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "France", FormalName: "French Republic", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "FR", ISO3: "FRA", Continent: "Europe", RegionUN: "Europe", Subregion: "Western Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Gabon", FormalName: "Gabonese Republic", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "GA", ISO3: "GAB", Continent: "Africa", RegionUN: "Africa", Subregion: "Middle Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "United Kingdom", FormalName: "United Kingdom of Great Britain and Northern Ireland", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "GB", ISO3: "GBR", Continent: "Europe", RegionUN: "Europe", Subregion: "Northern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Grenada", FormalName: "Grenada", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "GD", ISO3: "GRD", Continent: "North America", RegionUN: "America", Subregion: "Caribbean", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Georgia", FormalName: "Georgia", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "GE", ISO3: "GEO", Continent: "Asia", RegionUN: "Asia", Subregion: "Western Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "French Guiana", FormalName: "French Guiana", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "GF", ISO3: "GUF", Continent: "South America", RegionUN: "America", Subregion: "South America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Guernsey", FormalName: "Guernsey", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "GG", ISO3: "GGY", Continent: "Europe", RegionUN: "Europe", Subregion: "Northern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Ghana", FormalName: "Republic of Ghana", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "GH", ISO3: "GHA", Continent: "Africa", RegionUN: "Africa", Subregion: "Western Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Gibraltar", FormalName: "Gibraltar", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "GI", ISO3: "GIB", Continent: "Europe", RegionUN: "Europe", Subregion: "Southern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Greenland", FormalName: "Greenland", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "GL", ISO3: "GRL", Continent: "North America", RegionUN: "America", Subregion: "Northern America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Gambia", FormalName: "Republic of the Gambia", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "GM", ISO3: "GMB", Continent: "Africa", RegionUN: "Africa", Subregion: "Western Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Guinea", FormalName: "Republic of Guinea", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "GN", ISO3: "GIN", Continent: "Africa", RegionUN: "Africa", Subregion: "Western Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Guadeloupe", FormalName: "Guadeloupe", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "GP", ISO3: "GLP", Continent: "North America", RegionUN: "America", Subregion: "Caribbean", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Equatorial Guinea", FormalName: "Republic of Equatorial Guinea", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "GQ", ISO3: "GNQ", Continent: "Africa", RegionUN: "Africa", Subregion: "Middle Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Greece", FormalName: "Hellenic Republic", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "GR", ISO3: "GRC", Continent: "Europe", RegionUN: "Europe", Subregion: "Southern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "South Georgia and the South Sandwich Islands", FormalName: "South Georgia and the South Sandwich Islands", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "GS", ISO3: "SGS", Continent: "South America", RegionUN: "Antarctica", Subregion: "South America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Guatemala", FormalName: "Republic of Guatemala", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "GT", ISO3: "GTM", Continent: "North America", RegionUN: "America", Subregion: "Central America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Guam", FormalName: "Guam", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "GU", ISO3: "GUM", Continent: "Oceania", RegionUN: "Oceania", Subregion: "Micronesia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Guinea-Bissau", FormalName: "Republic of Guinea-Bissau", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "GW", ISO3: "GNB", Continent: "Africa", RegionUN: "Africa", Subregion: "Western Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Guyana", FormalName: "Republic of Guyana", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "GY", ISO3: "GUY", Continent: "South America", RegionUN: "America", Subregion: "South America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Hong Kong", FormalName: "Hong Kong Special Administrative Region of China", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "HK", ISO3: "HKG", Continent: "Asia", RegionUN: "Asia", Subregion: "Eastern Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Heard Island and McDonald Islands", FormalName: "Heard Island and McDonald Islands", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "HM", ISO3: "HMD", Continent: "Antarctica", RegionUN: "Antarctica", Subregion: "Australia and New Zealand", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Honduras", FormalName: "Republic of Honduras", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "HN", ISO3: "HND", Continent: "North America", RegionUN: "America", Subregion: "Central America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Croatia", FormalName: "Republic of Croatia", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "HR", ISO3: "HRV", Continent: "Europe", RegionUN: "Europe", Subregion: "Southern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Haiti", FormalName: "Republic of Haiti", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "HT", ISO3: "HTI", Continent: "North America", RegionUN: "America", Subregion: "Caribbean", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Hungary", FormalName: "Hungary", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "HU", ISO3: "HUN", Continent: "Europe", RegionUN: "Europe", Subregion: "Eastern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Indonesia", FormalName: "Republic of Indonesia", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "ID", ISO3: "IDN", Continent: "Asia", RegionUN: "Asia", Subregion: "South-eastern Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Ireland", FormalName: "Ireland", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "IE", ISO3: "IRL", Continent: "Europe", RegionUN: "Europe", Subregion: "Northern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Israel", FormalName: "State of Israel", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "IL", ISO3: "ISR", Continent: "Asia", RegionUN: "Asia", Subregion: "Western Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Isle of Man", FormalName: "Isle of Man", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "IM", ISO3: "IMN", Continent: "Europe", RegionUN: "Europe", Subregion: "Northern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "India", FormalName: "Republic of India", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "IN", ISO3: "IND", Continent: "Asia", RegionUN: "Asia", Subregion: "Southern Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "British Indian Ocean Territory", FormalName: "British Indian Ocean Territory", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "IO", ISO3: "IOT", Continent: "Asia", RegionUN: "Africa", Subregion: "Eastern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Iraq", FormalName: "Republic of Iraq", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "IQ", ISO3: "IRQ", Continent: "Asia", RegionUN: "Asia", Subregion: "Western Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Iran, Islamic Republic of", FormalName: "Islamic Republic of Iran", Abbrev: "Iran", NameAlt: "", Population: 0, GDP: 0, ISO2: "IR", ISO3: "IRN", Continent: "Asia", RegionUN: "Asia", Subregion: "Southern Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Iceland", FormalName: "Republic of Iceland", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "IS", ISO3: "ISL", Continent: "Europe", RegionUN: "Europe", Subregion: "Northern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Italy", FormalName: "Italian Republic", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "IT", ISO3: "ITA", Continent: "Europe", RegionUN: "Europe", Subregion: "Southern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Jersey", FormalName: "Jersey", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "JE", ISO3: "JEY", Continent: "Europe", RegionUN: "Europe", Subregion: "Northern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Jamaica", FormalName: "Jamaica", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "JM", ISO3: "JAM", Continent: "North America", RegionUN: "America", Subregion: "Caribbean", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Jordan", FormalName: "Hashemite Kingdom of Jordan", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "JO", ISO3: "JOR", Continent: "Asia", RegionUN: "Asia", Subregion: "Western Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Japan", FormalName: "Japan", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "JP", ISO3: "JPN", Continent: "Asia", RegionUN: "Asia", Subregion: "Eastern Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Kenya", FormalName: "Republic of Kenya", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "KE", ISO3: "KEN", Continent: "Africa", RegionUN: "Africa", Subregion: "Eastern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Kyrgyzstan", FormalName: "Kyrgyz Republic", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "KG", ISO3: "KGZ", Continent: "Asia", RegionUN: "Asia", Subregion: "Central Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Cambodia", FormalName: "Kingdom of Cambodia", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "KH", ISO3: "KHM", Continent: "Asia", RegionUN: "Asia", Subregion: "South-eastern Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Kiribati", FormalName: "Republic of Kiribati", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "KI", ISO3: "KIR", Continent: "Oceania", RegionUN: "Oceania", Subregion: "Micronesia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Comoros", FormalName: "Union of the Comoros", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "KM", ISO3: "COM", Continent: "Africa", RegionUN: "Africa", Subregion: "Eastern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Saint Kitts and Nevis", FormalName: "Saint Kitts and Nevis", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "KN", ISO3: "KNA", Continent: "North America", RegionUN: "America", Subregion: "Caribbean", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Korea, Democratic People's Republic of", FormalName: "Democratic People's Republic of Korea", Abbrev: "North Korea", NameAlt: "", Population: 0, GDP: 0, ISO2: "KP", ISO3: "PRK", Continent: "Asia", RegionUN: "Asia", Subregion: "Eastern Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Korea, Republic of", FormalName: "Korea, Republic of", Abbrev: "South Korea", NameAlt: "", Population: 0, GDP: 0, ISO2: "KR", ISO3: "KOR", Continent: "Asia", RegionUN: "Asia", Subregion: "Eastern Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Kuwait", FormalName: "State of Kuwait", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "KW", ISO3: "KWT", Continent: "Asia", RegionUN: "Asia", Subregion: "Western Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Cayman Islands", FormalName: "Cayman Islands", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "KY", ISO3: "CYM", Continent: "North America", RegionUN: "America", Subregion: "Caribbean", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Kazakhstan", FormalName: "Republic of Kazakhstan", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "KZ", ISO3: "KAZ", Continent: "Asia", RegionUN: "Asia", Subregion: "Central Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Lao People's Democratic Republic", FormalName: "Lao People's Democratic Republic", Abbrev: "Laos", NameAlt: "", Population: 0, GDP: 0, ISO2: "LA", ISO3: "LAO", Continent: "Asia", RegionUN: "Asia", Subregion: "South-eastern Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Lebanon", FormalName: "Lebanese Republic", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "LB", ISO3: "LBN", Continent: "Asia", RegionUN: "Asia", Subregion: "Western Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Saint Lucia", FormalName: "Saint Lucia", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "LC", ISO3: "LCA", Continent: "North America", RegionUN: "America", Subregion: "Caribbean", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Liechtenstein", FormalName: "Principality of Liechtenstein", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "LI", ISO3: "LIE", Continent: "Europe", RegionUN: "Europe", Subregion: "Western Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Sri Lanka", FormalName: "Democratic Socialist Republic of Sri Lanka", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "LK", ISO3: "LKA", Continent: "Asia", RegionUN: "Asia", Subregion: "Southern Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Liberia", FormalName: "Republic of Liberia", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "LR", ISO3: "LBR", Continent: "Africa", RegionUN: "Africa", Subregion: "Western Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Lesotho", FormalName: "Kingdom of Lesotho", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "LS", ISO3: "LSO", Continent: "Africa", RegionUN: "Africa", Subregion: "Southern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Lithuania", FormalName: "Republic of Lithuania", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "LT", ISO3: "LTU", Continent: "Europe", RegionUN: "Europe", Subregion: "Northern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Luxembourg", FormalName: "Grand Duchy of Luxembourg", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "LU", ISO3: "LUX", Continent: "Europe", RegionUN: "Europe", Subregion: "Western Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Latvia", FormalName: "Republic of Latvia", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "LV", ISO3: "LVA", Continent: "Europe", RegionUN: "Europe", Subregion: "Northern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Libya", FormalName: "Libya", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "LY", ISO3: "LBY", Continent: "Africa", RegionUN: "Africa", Subregion: "Northern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Morocco", FormalName: "Kingdom of Morocco", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "MA", ISO3: "MAR", Continent: "Africa", RegionUN: "Africa", Subregion: "Northern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Monaco", FormalName: "Principality of Monaco", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "MC", ISO3: "MCO", Continent: "Europe", RegionUN: "Europe", Subregion: "Western Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Moldova, Republic of", FormalName: "Republic of Moldova", Abbrev: "Moldova", NameAlt: "", Population: 0, GDP: 0, ISO2: "MD", ISO3: "MDA", Continent: "Europe", RegionUN: "Europe", Subregion: "Eastern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Montenegro", FormalName: "Montenegro", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "ME", ISO3: "MNE", Continent: "Europe", RegionUN: "Europe", Subregion: "Southern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Saint Martin (French part)", FormalName: "Saint Martin (French part)", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "MF", ISO3: "MAF", Continent: "North America", RegionUN: "America", Subregion: "Caribbean", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Madagascar", FormalName: "Republic of Madagascar", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "MG", ISO3: "MDG", Continent: "Africa", RegionUN: "Africa", Subregion: "Eastern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Marshall Islands", FormalName: "Republic of the Marshall Islands", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "MH", ISO3: "MHL", Continent: "Oceania", RegionUN: "Oceania", Subregion: "Micronesia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "North Macedonia", FormalName: "Republic of North Macedonia", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "MK", ISO3: "MKD", Continent: "Europe", RegionUN: "Europe", Subregion: "Southern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Mali", FormalName: "Republic of Mali", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "ML", ISO3: "MLI", Continent: "Africa", RegionUN: "Africa", Subregion: "Western Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Myanmar", FormalName: "Republic of Myanmar", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "MM", ISO3: "MMR", Continent: "Asia", RegionUN: "Asia", Subregion: "South-eastern Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Mongolia", FormalName: "Mongolia", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "MN", ISO3: "MNG", Continent: "Asia", RegionUN: "Asia", Subregion: "Eastern Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Macao", FormalName: "Macao Special Administrative Region of China", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "MO", ISO3: "MAC", Continent: "Asia", RegionUN: "Asia", Subregion: "Eastern Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Northern Mariana Islands", FormalName: "Commonwealth of the Northern Mariana Islands", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "MP", ISO3: "MNP", Continent: "Oceania", RegionUN: "Oceania", Subregion: "Micronesia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Martinique", FormalName: "Martinique", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "MQ", ISO3: "MTQ", Continent: "North America", RegionUN: "America", Subregion: "Caribbean", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Mauritania", FormalName: "Islamic Republic of Mauritania", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "MR", ISO3: "MRT", Continent: "Africa", RegionUN: "Africa", Subregion: "Western Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Montserrat", FormalName: "Montserrat", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "MS", ISO3: "MSR", Continent: "North America", RegionUN: "America", Subregion: "Caribbean", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Malta", FormalName: "Republic of Malta", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "MT", ISO3: "MLT", Continent: "Europe", RegionUN: "Europe", Subregion: "Southern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Mauritius", FormalName: "Republic of Mauritius", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "MU", ISO3: "MUS", Continent: "Africa", RegionUN: "Africa", Subregion: "Eastern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Maldives", FormalName: "Republic of Maldives", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "MV", ISO3: "MDV", Continent: "Asia", RegionUN: "Asia", Subregion: "Southern Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Malawi", FormalName: "Republic of Malawi", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "MW", ISO3: "MWI", Continent: "Africa", RegionUN: "Africa", Subregion: "Eastern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Mexico", FormalName: "United Mexican States", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "MX", ISO3: "MEX", Continent: "North America", RegionUN: "America", Subregion: "Central America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Malaysia", FormalName: "Malaysia", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "MY", ISO3: "MYS", Continent: "Asia", RegionUN: "Asia", Subregion: "South-eastern Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Mozambique", FormalName: "Republic of Mozambique", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "MZ", ISO3: "MOZ", Continent: "Africa", RegionUN: "Africa", Subregion: "Eastern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Namibia", FormalName: "Republic of Namibia", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "NA", ISO3: "NAM", Continent: "Africa", RegionUN: "Africa", Subregion: "Southern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "New Caledonia", FormalName: "New Caledonia", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "NC", ISO3: "NCL", Continent: "Oceania", RegionUN: "Oceania", Subregion: "Melanesia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Niger", FormalName: "Republic of the Niger", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "NE", ISO3: "NER", Continent: "Africa", RegionUN: "Africa", Subregion: "Western Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Norfolk Island", FormalName: "Norfolk Island", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "NF", ISO3: "NFK", Continent: "Oceania", RegionUN: "Oceania", Subregion: "Australia and New Zealand", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Nigeria", FormalName: "Federal Republic of Nigeria", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "NG", ISO3: "NGA", Continent: "Africa", RegionUN: "Africa", Subregion: "Western Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Nicaragua", FormalName: "Republic of Nicaragua", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "NI", ISO3: "NIC", Continent: "North America", RegionUN: "America", Subregion: "Central America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Netherlands", FormalName: "Kingdom of the Netherlands", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "NL", ISO3: "NLD", Continent: "Europe", RegionUN: "Europe", Subregion: "Western Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Norway", FormalName: "Kingdom of Norway", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "NO", ISO3: "NOR", Continent: "Europe", RegionUN: "Europe", Subregion: "Northern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Nepal", FormalName: "Federal Democratic Republic of Nepal", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "NP", ISO3: "NPL", Continent: "Asia", RegionUN: "Asia", Subregion: "Southern Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Nauru", FormalName: "Republic of Nauru", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "NR", ISO3: "NRU", Continent: "Oceania", RegionUN: "Oceania", Subregion: "Polynesia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Niue", FormalName: "Niue", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "NU", ISO3: "NIU", Continent: "Oceania", RegionUN: "Oceania", Subregion: "Polynesia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "New Zealand", FormalName: "New Zealand", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "NZ", ISO3: "NZL", Continent: "Oceania", RegionUN: "Oceania", Subregion: "Australia and New Zealand", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Oman", FormalName: "Sultanate of Oman", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "OM", ISO3: "OMN", Continent: "Asia", RegionUN: "Asia", Subregion: "Western Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Panama", FormalName: "Republic of Panama", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "PA", ISO3: "PAN", Continent: "North America", RegionUN: "America", Subregion: "Central America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Peru", FormalName: "Republic of Peru", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "PE", ISO3: "PER", Continent: "South America", RegionUN: "America", Subregion: "South America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "French Polynesia", FormalName: "French Polynesia", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "PF", ISO3: "PYF", Continent: "Oceania", RegionUN: "Oceania", Subregion: "Polynesia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Papua New Guinea", FormalName: "Independent State of Papua New Guinea", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "PG", ISO3: "PNG", Continent: "Oceania", RegionUN: "Oceania", Subregion: "Melanesia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Philippines", FormalName: "Republic of the Philippines", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "PH", ISO3: "PHL", Continent: "Asia", RegionUN: "Asia", Subregion: "South-eastern Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Pakistan", FormalName: "Islamic Republic of Pakistan", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "PK", ISO3: "PAK", Continent: "Asia", RegionUN: "Asia", Subregion: "Southern Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Poland", FormalName: "Republic of Poland", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "PL", ISO3: "POL", Continent: "Europe", RegionUN: "Europe", Subregion: "Eastern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Saint Pierre and Miquelon", FormalName: "Saint Pierre and Miquelon", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "PM", ISO3: "SPM", Continent: "North America", RegionUN: "America", Subregion: "Northern America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Pitcairn", FormalName: "Pitcairn", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "PN", ISO3: "PCN", Continent: "Oceania", RegionUN: "Oceania", Subregion: "Polynesia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Puerto Rico", FormalName: "Puerto Rico", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "PR", ISO3: "PRI", Continent: "North America", RegionUN: "America", Subregion: "Caribbean", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Palestine, State of", FormalName: "the State of Palestine", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "PS", ISO3: "PSE", Continent: "Asia", RegionUN: "Asia", Subregion: "Western Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Portugal", FormalName: "Portuguese Republic", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "PT", ISO3: "PRT", Continent: "Europe", RegionUN: "Europe", Subregion: "Southern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Palau", FormalName: "Republic of Palau", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "PW", ISO3: "PLW", Continent: "Oceania", RegionUN: "Oceania", Subregion: "Micronesia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Paraguay", FormalName: "Republic of Paraguay", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "PY", ISO3: "PRY", Continent: "South America", RegionUN: "America", Subregion: "South America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Qatar", FormalName: "State of Qatar", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "QA", ISO3: "QAT", Continent: "Asia", RegionUN: "Asia", Subregion: "Western Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Réunion", FormalName: "Réunion", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "RE", ISO3: "REU", Continent: "Africa", RegionUN: "Africa", Subregion: "Eastern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Romania", FormalName: "Romania", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "RO", ISO3: "ROU", Continent: "Europe", RegionUN: "Europe", Subregion: "Eastern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Serbia", FormalName: "Republic of Serbia", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "RS", ISO3: "SRB", Continent: "Europe", RegionUN: "Europe", Subregion: "Southern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Russian Federation", FormalName: "Russian Federation", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "RU", ISO3: "RUS", Continent: "Europe", RegionUN: "Europe", Subregion: "Eastern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Rwanda", FormalName: "Rwandese Republic", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "RW", ISO3: "RWA", Continent: "Africa", RegionUN: "Africa", Subregion: "Eastern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Saudi Arabia", FormalName: "Kingdom of Saudi Arabia", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "SA", ISO3: "SAU", Continent: "Asia", RegionUN: "Asia", Subregion: "Western Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Solomon Islands", FormalName: "Solomon Islands", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "SB", ISO3: "SLB", Continent: "Oceania", RegionUN: "Oceania", Subregion: "Melanesia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Seychelles", FormalName: "Republic of Seychelles", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "SC", ISO3: "SYC", Continent: "Africa", RegionUN: "Africa", Subregion: "Eastern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Sudan", FormalName: "Republic of the Sudan", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "SD", ISO3: "SDN", Continent: "Africa", RegionUN: "Africa", Subregion: "Northern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Sweden", FormalName: "Kingdom of Sweden", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "SE", ISO3: "SWE", Continent: "Europe", RegionUN: "Europe", Subregion: "Northern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Singapore", FormalName: "Republic of Singapore", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "SG", ISO3: "SGP", Continent: "Asia", RegionUN: "Asia", Subregion: "South-eastern Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Saint Helena, Ascension and Tristan da Cunha", FormalName: "Saint Helena, Ascension and Tristan da Cunha", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "SH", ISO3: "SHN", Continent: "Africa", RegionUN: "Africa", Subregion: "Western Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Slovenia", FormalName: "Republic of Slovenia", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "SI", ISO3: "SVN", Continent: "Europe", RegionUN: "Europe", Subregion: "Southern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Svalbard and Jan Mayen", FormalName: "Svalbard and Jan Mayen", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "SJ", ISO3: "SJM", Continent: "Europe", RegionUN: "Europe", Subregion: "Northern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Slovakia", FormalName: "Slovak Republic", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "SK", ISO3: "SVK", Continent: "Europe", RegionUN: "Europe", Subregion: "Eastern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Sierra Leone", FormalName: "Republic of Sierra Leone", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "SL", ISO3: "SLE", Continent: "Africa", RegionUN: "Africa", Subregion: "Western Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "San Marino", FormalName: "Republic of San Marino", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "SM", ISO3: "SMR", Continent: "Europe", RegionUN: "Europe", Subregion: "Southern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Senegal", FormalName: "Republic of Senegal", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "SN", ISO3: "SEN", Continent: "Africa", RegionUN: "Africa", Subregion: "Western Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Somalia", FormalName: "Federal Republic of Somalia", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "SO", ISO3: "SOM", Continent: "Africa", RegionUN: "Africa", Subregion: "Eastern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Suriname", FormalName: "Republic of Suriname", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "SR", ISO3: "SUR", Continent: "South America", RegionUN: "America", Subregion: "South America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "South Sudan", FormalName: "Republic of South Sudan", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "SS", ISO3: "SSD", Continent: "Africa", RegionUN: "Africa", Subregion: "Eastern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Sao Tome and Principe", FormalName: "Democratic Republic of Sao Tome and Principe", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "ST", ISO3: "STP", Continent: "Africa", RegionUN: "Africa", Subregion: "Middle Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "El Salvador", FormalName: "Republic of El Salvador", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "SV", ISO3: "SLV", Continent: "North America", RegionUN: "America", Subregion: "Central America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Sint Maarten (Dutch part)", FormalName: "Sint Maarten (Dutch part)", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "SX", ISO3: "SXM", Continent: "North America", RegionUN: "America", Subregion: "Caribbean", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Syrian Arab Republic", FormalName: "Syrian Arab Republic", Abbrev: "Syria", NameAlt: "", Population: 0, GDP: 0, ISO2: "SY", ISO3: "SYR", Continent: "Asia", RegionUN: "Asia", Subregion: "Western Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Eswatini", FormalName: "Kingdom of Eswatini", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "SZ", ISO3: "SWZ", Continent: "Africa", RegionUN: "Africa", Subregion: "Southern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Turks and Caicos Islands", FormalName: "Turks and Caicos Islands", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "TC", ISO3: "TCA", Continent: "North America", RegionUN: "America", Subregion: "Caribbean", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Chad", FormalName: "Republic of Chad", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "TD", ISO3: "TCD", Continent: "Africa", RegionUN: "Africa", Subregion: "Middle Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "French Southern Territories", FormalName: "French Southern Territories", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "TF", ISO3: "ATF", Continent: "Antarctica", RegionUN: "Africa", Subregion: "Eastern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Togo", FormalName: "Togolese Republic", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "TG", ISO3: "TGO", Continent: "Africa", RegionUN: "Africa", Subregion: "Western Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Thailand", FormalName: "Kingdom of Thailand", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "TH", ISO3: "THA", Continent: "Asia", RegionUN: "Asia", Subregion: "South-eastern Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Tajikistan", FormalName: "Republic of Tajikistan", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "TJ", ISO3: "TJK", Continent: "Asia", RegionUN: "Asia", Subregion: "Central Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Tokelau", FormalName: "Tokelau", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "TK", ISO3: "TKL", Continent: "Oceania", RegionUN: "Oceania", Subregion: "Polynesia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Timor-Leste", FormalName: "Democratic Republic of Timor-Leste", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "TL", ISO3: "TLS", Continent: "Asia", RegionUN: "Asia", Subregion: "South-eastern Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Turkmenistan", FormalName: "Turkmenistan", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "TM", ISO3: "TKM", Continent: "Asia", RegionUN: "Asia", Subregion: "Central Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Tunisia", FormalName: "Republic of Tunisia", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "TN", ISO3: "TUN", Continent: "Africa", RegionUN: "Africa", Subregion: "Northern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Tonga", FormalName: "Kingdom of Tonga", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "TO", ISO3: "TON", Continent: "Oceania", RegionUN: "Oceania", Subregion: "Polynesia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Türkiye", FormalName: "Republic of Türkiye", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "TR", ISO3: "TUR", Continent: "Asia", RegionUN: "Asia", Subregion: "Western Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Trinidad and Tobago", FormalName: "Republic of Trinidad and Tobago", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "TT", ISO3: "TTO", Continent: "North America", RegionUN: "America", Subregion: "Caribbean", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Tuvalu", FormalName: "Tuvalu", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "TV", ISO3: "TUV", Continent: "Oceania", RegionUN: "Oceania", Subregion: "Polynesia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Taiwan, Province of China", FormalName: "Taiwan, Province of China", Abbrev: "Taiwan", NameAlt: "", Population: 0, GDP: 0, ISO2: "TW", ISO3: "TWN", Continent: "Asia", RegionUN: "Asia", Subregion: "Eastern Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Tanzania, United Republic of", FormalName: "United Republic of Tanzania", Abbrev: "Tanzania", NameAlt: "", Population: 0, GDP: 0, ISO2: "TZ", ISO3: "TZA", Continent: "Africa", RegionUN: "Africa", Subregion: "Eastern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Ukraine", FormalName: "Ukraine", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "UA", ISO3: "UKR", Continent: "Europe", RegionUN: "Europe", Subregion: "Eastern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Uganda", FormalName: "Republic of Uganda", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "UG", ISO3: "UGA", Continent: "Africa", RegionUN: "Africa", Subregion: "Eastern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "United States Minor Outlying Islands", FormalName: "United States Minor Outlying Islands", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "UM", ISO3: "UMI", Continent: "Oceania", RegionUN: "Oceania", Subregion: "Micronesia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "United States", FormalName: "United States of America", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "US", ISO3: "USA", Continent: "North America", RegionUN: "America", Subregion: "Northern America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Uruguay", FormalName: "Eastern Republic of Uruguay", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "UY", ISO3: "URY", Continent: "South America", RegionUN: "America", Subregion: "South America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Uzbekistan", FormalName: "Republic of Uzbekistan", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "UZ", ISO3: "UZB", Continent: "Asia", RegionUN: "Asia", Subregion: "Central Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Holy See (Vatican City State)", FormalName: "Holy See (Vatican City State)", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "VA", ISO3: "VAT", Continent: "Europe", RegionUN: "Europe", Subregion: "Southern Europe", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Saint Vincent and the Grenadines", FormalName: "Saint Vincent and the Grenadines", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "VC", ISO3: "VCT", Continent: "North America", RegionUN: "America", Subregion: "Caribbean", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Venezuela, Bolivarian Republic of", FormalName: "Bolivarian Republic of Venezuela", Abbrev: "Venezuela", NameAlt: "", Population: 0, GDP: 0, ISO2: "VE", ISO3: "VEN", Continent: "South America", RegionUN: "America", Subregion: "South America", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Virgin Islands, British", FormalName: "British Virgin Islands", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "VG", ISO3: "VGB", Continent: "North America", RegionUN: "America", Subregion: "Caribbean", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Virgin Islands, U.S.", FormalName: "Virgin Islands of the United States", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "VI", ISO3: "VIR", Continent: "North America", RegionUN: "America", Subregion: "Caribbean", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Viet Nam", FormalName: "Socialist Republic of Viet Nam", Abbrev: "Vietnam", NameAlt: "", Population: 0, GDP: 0, ISO2: "VN", ISO3: "VNM", Continent: "Asia", RegionUN: "Asia", Subregion: "South-eastern Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Vanuatu", FormalName: "Republic of Vanuatu", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "VU", ISO3: "VUT", Continent: "Oceania", RegionUN: "Oceania", Subregion: "Melanesia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Wallis and Futuna", FormalName: "Wallis and Futuna", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "WF", ISO3: "WLF", Continent: "Oceania", RegionUN: "Oceania", Subregion: "Polynesia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Samoa", FormalName: "Independent State of Samoa", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "WS", ISO3: "WSM", Continent: "Oceania", RegionUN: "Oceania", Subregion: "Polynesia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Yemen", FormalName: "Republic of Yemen", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "YE", ISO3: "YEM", Continent: "Asia", RegionUN: "Asia", Subregion: "Western Asia", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Mayotte", FormalName: "Mayotte", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "YT", ISO3: "MYT", Continent: "Africa", RegionUN: "Africa", Subregion: "Eastern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "South Africa", FormalName: "Republic of South Africa", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "ZA", ISO3: "ZAF", Continent: "Africa", RegionUN: "Africa", Subregion: "Southern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Zambia", FormalName: "Republic of Zambia", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "ZM", ISO3: "ZMB", Continent: "Africa", RegionUN: "Africa", Subregion: "Eastern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
    {Name: "Zimbabwe", FormalName: "Republic of Zimbabwe", Abbrev: "", NameAlt: "", Population: 0, GDP: 0, ISO2: "ZW", ISO3: "ZWE", Continent: "Africa", RegionUN: "Africa", Subregion: "Eastern Africa", RegionWB: "", LabelX: 0.0, LabelY: 0.0},
}

var countryAliasISO2 = map[string]string{
    "burma": "MM",
    "myramar": "MM",
    "myanmar": "MM",
    "zaire": "CD",
    "czechoslovakia": "CZ",
    "yugoslavia": "RS",
    "swaziland": "SZ",
    "east germany": "DE",
    "west germany": "DE",
    "persia": "IR",
    "siam": "TH",
    "holland": "NL",
    "ivorycoast": "CI",
    "capeverde": "CV",
    "macedonia": "MK",
    "fyrom": "MK",
    "greatbritain": "GB",
    "britain": "GB",
    "uk": "GB",
    "england": "GB",
    "el": "GR",
    "tw": "TW",
}

var countryRegexISO2 = map[string]string{
    "AD": "andorra",
    "AE": "emirates|^u\\.?a\\.?e\\.?$|united.?arab.?em",
    "AF": "afghan",
    "AG": "antigua",
    "AI": "anguill?a",
    "AL": "albania",
    "AM": "armenia",
    "AO": "angola",
    "AQ": "antarctica",
    "AR": "argentin",
    "AS": "^(?=.*americ).*samoa",
    "AT": "austria",
    "AU": "australia",
    "AW": "^(?!.*bonaire).*\\baruba",
    "AX": "\\b(a|å)land",
    "AZ": "azerbaijan",
    "BA": "herzegovina|bosnia",
    "BB": "barbados",
    "BD": "bangladesh|^(?=.*east).*paki?stan",
    "BE": "^(?!.*luxem).*belgium",
    "BF": "burkina|\\bfaso|upper.?volta",
    "BG": "bulgaria",
    "BH": "bahrain",
    "BI": "burundi",
    "BJ": "benin|dahome",
    "BL": "barth|barts",
    "BM": "bermuda",
    "BN": "brunei",
    "BO": "bolivia",
    "BQ": "^bonaire|(?=.*bonaire).*eustatius|^(?=.*carib).*netherlands|\\bbes.?islands",
    "BR": "brazil",
    "BS": "bahamas",
    "BT": "bhutan",
    "BV": "bouvet",
    "BW": "botswana|bechuana|botsuana",
    "BY": "belarus|byelo",
    "BZ": "belize|^(?=.*british).*honduras",
    "CA": "canada",
    "CC": "\\bcocos|keeling",
    "CD": "\\bdem.*congo|congo.*\\bdem|congo.*\\bdr|\\bdr.*congo|\\bd\\.?r\\.?c|\\bd\\.?r\\.?o\\.?c|\\br\\.?d\\.?c|belgian.?congo|congo.?free.?state|kinshasa|zaire|l\\w{1,2}opoldville|^the\\ congo$|^RDC$|^DROC$|\\bcongo.*dem.*",
    "CF": "central.?african.?rep.*",
    "CG": "^(?!.*\\bdem)(?!.*\\bdr)(?!.*kinshasa)(?!.*zaire)(?!.*belg)(?!.*l\\w{1,2}opoldville)(?!.*free)(^rep.*).*\\bcongo.*(?!.*\\bdem)(?!.*\\bdr).*|\\bwest.*congo|^congo[,;\\s]*(?!.*dem)rep.*?$|^congo$|\\bcongo.*brazza.*",
    "CH": "switz|swiss",
    "CI": ".*(ivoire|ivory)",
    "CK": "\\bcook",
    "CL": "\\bchile",
    "CM": "cameroon",
    "CN": "^(?!repub)(?!taiwan)(?!hong.*kong)(?!macao).*china(?!.*hong.*kong)(?!.*macao)|^PRC$",
    "CO": "colombia",
    "CR": "costa.?rica",
    "CU": "\\bcuba",
    "CV": "(cabo|cape) *verde",
    "CW": "\\bcura(c|ç)ao",
    "CX": "christmas",
    "CY": "cyprus",
    "CZ": "^(?=.*rep).*czech.*|czechia|bohemia|.*czech.*",
    "DE": "^(?!e|w)(fed)?.*germany(?!,? *e|,? *w)(,? *)(\\bfed)?",
    "DJ": "djibouti",
    "DK": "denmark",
    "DM": "dominica(?!n)",
    "DO": "dominican",
    "DZ": "algeria",
    "EC": "ecuador",
    "EE": "estonia",
    "EG": "egypt",
    "EH": "\\bw.*sahara",
    "ER": "eritrea",
    "ES": "spain",
    "ET": "ethiopia|abyssinia",
    "FI": "finland",
    "FJ": "fiji",
    "FK": "falkland|malvinas",
    "FM": "micronesia",
    "FO": "faroe|faeroe",
    "FR": "^(?!.*\\bdep).*france|french.?republic|\\bgaul",
    "GA": "gab(o|u)n",
    "GB": ".*(united.?kingdom|britain|^u\\.?k\\.?$|gb)|england",
    "GD": "grenada",
    "GE": "^(?!.*south).*georgia(?!.*US.*)",
    "GF": "^(?=.*french).*gu(i|y)ana|^(?!.*brit)(?!.*dut).*guiana",
    "GG": "guernsey",
    "GH": "ghana|gold.?coast",
    "GI": "gibraltar",
    "GL": "greenland",
    "GM": "gambia",
    "GN": "^(?!.*eq)(?!.*span)(?!.*bissau)(?!.*pap)(?!.*new)(?!p.*n.*).*guinea",
    "GP": "guadeloupe",
    "GQ": "guine.*eq|eq.*guine|^(?=.*span).*guinea",
    "GR": "greece|hellenic|hellas",
    "GS": "south.?georgia|sandwich",
    "GT": "guatemala",
    "GU": "\\bguam",
    "GW": "^(.*portu).*gu(i|y)nea|gu(y|i)nea.*bissau",
    "GY": "^(?!.*fren)(?!.*dut).*\\bguyana|^(.*brit).*gu(i|y)ana",
    "HK": ".*hong.*kong|hksar",
    "HM": "heard.*mc.*donald",
    "HN": "^(?!.*brit).*honduras",
    "HR": "croatia|hrvatska",
    "HT": "(ha(i|\\xef|\\xc3\\xaf)ti)",
    "HU": "hungary",
    "ID": "indonesia",
    "IE": "^(?!.*north.*).*ireland",
    "IL": "israel",
    "IM": "^(?=.*isle).*\\bman",
    "IN": "^(?!\\D*(?:bassas))\\D*india(?!.*ocea)(?!na)",
    "IO": "br.*indian.?ocean",
    "IQ": "\\biraq|mesopotamia",
    "IR": "\\biran|persia",
    "IS": "iceland",
    "IT": ".*italy|.*italia.*",
    "JE": "^(?!.*new).*jersey",
    "JM": "jamaica",
    "JO": "jordan",
    "JP": "japan",
    "KE": "kenya|british.?east.?africa|east.?africa.?prot",
    "KG": "kyrgyz|kirghiz",
    "KH": "cambodia|kampuchea|khmer|^p\\.?r\\.?k\\.?$",
    "KI": "kiribati",
    "KM": "comoro",
    "KN": "kitts|\\bnevis",
    "KP": "^(?=.*dem).*\\bkorea|^(?=.*peo).*\\bkorea|^(?=.*nor).*\\bkorea|\\bd\\.?p\\.?r\\.|.*dpr.*|^n.*korea",
    "KR": "^(?!.*dem)(?!.*peo)(?!.*nor)(?!.*n)(?!.*dpr)(?!d\\.p\\.r).*\\bkorea|\\br\\.?o\\.?k\\b",
    "KW": "kuwait",
    "KY": "cayman",
    "KZ": "kazak",
    "LA": "\\blaos?\\b",
    "LB": "lebanon|lebanese",
    "LC": "\\blucia",
    "LI": "liechtenstein",
    "LK": "sri.?lanka|ceylon",
    "LR": "liberia",
    "LS": "lesotho|basuto",
    "LT": "lithuania",
    "LU": "^(?!.*belg).*luxem",
    "LV": "latvia",
    "LY": "libya",
    "MA": "morocco|\\bmaroc",
    "MC": "monaco",
    "MD": "moldov|b(a|e)ssarabia",
    "ME": "^(?!.*serbia).*montenegro",
    "MF": "^(?!.*maarten)(?!.*saba)(?!.*dutch).*martin\\b",
    "MG": "madagascar|malagasy",
    "MH": "marshall",
    "MK": "macedonia|^f\\.?y\\.?r\\.?o\\.?m\\.?$",
    "ML": "\\bmali\\b",
    "MM": "myanmar|burma",
    "MN": "mongolia",
    "MO": ".*maca(o|u)",
    "MP": "mariana",
    "MQ": "martinique",
    "MR": "mauritania",
    "MS": "montserrat",
    "MT": "\\bmalta",
    "MU": "mauritius",
    "MV": "maldive",
    "MW": "malawi|nyasa",
    "MX": "^(?!.*new).*mexi(?!.*city)",
    "MY": "malaysia",
    "MZ": "mozambique",
    "NA": "namibia",
    "NC": "new.?caledonia",
    "NE": "\\bniger(?!ia)",
    "NF": "norfolk.*is",
    "NG": "nigeria",
    "NI": "nicaragua",
    "NL": "^(?!.*\\bant)(?!.*\\bcarib).*netherlands",
    "NO": "norway",
    "NP": "nepal",
    "NR": "nauru",
    "NU": "niue",
    "NZ": "(new|n).*zealand",
    "OM": "\\boman|trucial",
    "PA": "panama",
    "PE": "peru",
    "PF": "french.?polynesia",
    "PG": "\\bp.*\\bn.*\\bguin.*|^p\\.?n\\.?g\\.?$|new.?guinea",
    "PH": "philippines",
    "PK": "^(?!.*east).*paki?stan",
    "PL": "poland",
    "PM": "miquelon",
    "PN": "pitcairn",
    "PR": "puerto.?rico",
    "PS": "palestin|\\bgaza|west.?bank",
    "PT": "portugal|portuguese",
    "PW": "palau",
    "PY": "paraguay",
    "QA": "qatar",
    "RE": "reunion|réunion",
    "RO": "r(o|u|ou)mania",
    "RS": "^(?!.*monte).*serbia.*",
    "RU": "\\brussia",
    "RW": "rwanda",
    "SA": "\\bsa\\w*.?arabia",
    "SB": "solomon",
    "SC": "seychell",
    "SD": "^(?!.*\\bs(?!u)).*sudan",
    "SE": "swedish|sweden(?!.*except)",
    "SG": "singapore",
    "SH": "helena",
    "SI": "slovenia",
    "SJ": "^(?!norway).*svalbard",
    "SK": "^(?!.*cze).*slovak",
    "SL": "sierra",
    "SM": "san.?marino",
    "SN": "senegal",
    "SO": "somali",
    "SR": "surinam|dutch.?gu(i|y)ana",
    "SS": "\\bs\\w*.?sudan",
    "ST": "tome|tomé",
    "SV": "el.?salvador",
    "SX": "^(?!.*martin)(?!.*saba).*maarten|dutch.*martin|martin.*dutch",
    "SY": "syria",
    "SZ": "swaziland|eswatini",
    "TC": "turks",
    "TD": "\\bchad",
    "TF": "french.?southern|\\bfr.*\\bso.*\\ban.*\\b\\bt",
    "TG": "togo",
    "TH": "thailand|\\bsiam",
    "TJ": "tajik",
    "TK": "tokelau",
    "TL": "^(?=.*leste).*timor|^(?=.*east).*timor",
    "TM": "turk-?men",
    "TN": "tunisia",
    "TO": "tonga",
    "TR": "t[ü|u]rk[i|e]y",
    "TT": "trinidad|tobago",
    "TV": "tuvalu",
    "TW": ".*taiwan|.*taipei|.*formosa|^(?!.*\\bdem)(?!.*\\bpe)(?!.*\\bdr)(^rep.*).*\\bchina.*(?!.*\\bdem.*)(?!\\bpe.*)(?!.*\\bdr.*).*|^ROC$|^taiwan r\\.?o\\.?c\\.?$",
    "TZ": "tanzania(?!: zan.*)",
    "UA": "ukrain",
    "UG": "uganda",
    "UM": "minor.?outlying.?is",
    "US": "^(?!.*islands).*united.?states|^u\\.?s\\.?a\\.?$|^u\\.?s\\.?$",
    "UY": "uruguay",
    "UZ": "uzbek",
    "VA": "holy.?see|vatican|papal.?st",
    "VC": "vincent",
    "VE": "venezuela",
    "VG": "^(?=.*\\bu\\.?\\s?k).*virgin|^(?=.*br.*).*virgin|^(?=.*kingdom).*virgin|BVI",
    "VI": "^(?=.*\\bu\\.?\\s?s).*virgin|^(?=.*states).*virgin",
    "VN": "^((?!n|s|.*republic)|(?=.*socialist)).*viet.?nam(?! *,? *n| *,? *s)",
    "VU": "vanuatu|new.?hebrides",
    "WF": "futuna|wallis",
    "WS": "^(?!.*amer.*)samoa|(\\bindep.*samoa)|^west.*samoa",
    "YE": "yemen",
    "YT": "mayotte",
    "ZA": "\\bs(\\.|outh)(?!.*sahar).*africa|^r\\.?s\\.?a\\.?$",
    "ZM": "zambia|northern.?rhodesia",
    "ZW": "zimbabwe|^(?!.*northern).*rhodesia",
}
